groups: []
resources:
- name: pivnet-opsmgr
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: ops-manager
    product_version: {{opsman_major_minor_version}}
    sort_by: semver
- name: pcf-pipelines-tarball
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: pcf-automation
    product_version: v0.22.0
- name: schedule
  type: time
  source:
    days:
    - Sunday
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday
    - Saturday
    interval: 30m
    location: America/Los_Angeles
    start: 12:00 AM
    stop: 11:59 PM
resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
jobs:
- name: regulator
  plan:
  - get: schedule
    trigger: true
  - get: pivnet-opsmgr
    params:
      globs: []
- name: upgrade-opsmgr
  serial: true
  plan:
  - aggregate:
    - get: pivnet-opsmgr
      passed:
      - regulator
      trigger: true
      params:
        globs:
        - '*GCP.yml'
    - do:
      - get: pcf-pipelines-tarball
      - task: unpack-tarball
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: czero/rootfs
          run:
            path: bash
            args:
            - -c
            - tar -xvf pcf-pipelines-tarball/*.tgz
          inputs:
          - name: pcf-pipelines-tarball
            path: ""
          outputs:
          - name: pcf-pipelines
            path: ""
  - task: wait-opsman-clear
    file: pcf-pipelines/tasks/wait-opsman-clear/task.yml
    params:
      OPSMAN_CLIENT_ID: {{opsman_client_id}}
      OPSMAN_CLIENT_SECRET: {{opsman_client_secret}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
  - aggregate:
    - task: export-opsmgr-settings
      file: pcf-pipelines/tasks/export-opsmgr-settings/task.yml
      params:
        OPSMAN_CLIENT_ID: {{opsman_client_id}}
        OPSMAN_CLIENT_SECRET: {{opsman_client_secret}}
        OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
        OPSMAN_PASSWORD: {{opsman_admin_password}}
        OPSMAN_SETTINGS_FILENAME: installation.zip
        OPSMAN_USERNAME: {{opsman_admin_username}}
    - task: exported-opsmgr-diagnostic-report
      file: pcf-pipelines/tasks/export-opsmgr-diagnostic-report/task.yml
      params:
        OPSMAN_CLIENT_ID: {{opsman_client_id}}
        OPSMAN_CLIENT_SECRET: {{opsman_client_secret}}
        OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
        OPSMAN_PASSWORD: {{opsman_admin_password}}
        OPSMAN_USERNAME: {{opsman_admin_username}}
  - task: create-cliaas-config
    file: pcf-pipelines/upgrade-ops-manager/gcp/tasks/create-cliaas-config/task.yml
    params:
      GCP_PROJECT_ID: {{gcp_project_id}}
      GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
      GCP_ZONE: {{gcp_zone}}
      PIVNET_IMAGE_REGION: {{pivnet_image_region}}
  - task: replace-opsman-vm
    file: pcf-pipelines/tasks/replace-vm/task.yml
    params:
      VM_IDENTIFIER: {{existing_opsman_vm_name}}
  - task: import-opsmgr-settings
    file: pcf-pipelines/tasks/import-opsmgr-settings/task.yml
    params:
      OPSMAN_CLIENT_ID: {{opsman_client_id}}
      OPSMAN_CLIENT_SECRET: {{opsman_client_secret}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_PASSPHRASE: {{opsman_passphrase}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_SETTINGS_FILENAME: installation.zip
      OPSMAN_USERNAME: {{opsman_admin_username}}
  - task: download-stemcells
    file: pcf-pipelines/tasks/download-pivnet-stemcells/task.yml
    params:
      API_TOKEN: {{pivnet_token}}
      IAAS_TYPE: google
  - task: restore-stemcells
    file: pcf-pipelines/tasks/restore-stemcells/task.yml
    params:
      OPSMAN_CLIENT_ID: {{opsman_client_id}}
      OPSMAN_CLIENT_SECRET: {{opsman_client_secret}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
  - task: apply-changes
    file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_CLIENT_ID: {{opsman_client_id}}
      OPSMAN_CLIENT_SECRET: {{opsman_client_secret}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
